### ISSUE TITLE
Tooltip is display behind parent

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [stefanwalther/sense-calendar-heatmap#3]
![screen shot 2015-02-27 at 10 22 32](https://cloud.githubusercontent.com/assets/9255321/6410859/ad0b1bf4-be6a-11e4-8916-8031f466588a.png)

I've reposition the tooltip and gave it a new width, but even with a z-index i haven't yet manage to sort this one. Needs a bit more attention so i will get back to it.
The new width is 100px
and on the mouseover subtracting 30 and adding 15 for X and Y:

divTooltip.html( 'Date: ' + d.Date + '<br/>' + (!_.isEmpty( data[d.Date] ) ? data[d.Date].ToolTip : '') )
    .style( 'left', (d3.event.pageX - leftOffset - 30) + 'px' )
    .style( 'top', (d3.event.pageY - divTooltip.attr( 'height' ) - topOffset + 15) + 'px' );

**Comment by stefanwalther** [comment]
Hi, yes, I am aware of that, have to change the tooltip implementation completely ...
