### ISSUE TITLE
2 Instances in the same App render same metadata in Sense 1.0.2

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [stefanwalther/sense-calendar-heatmap#4]
This is due to usage of destroySessionObject which has been introduced in 1.1

**Comment by stefanwalther** [comment]
OK, thx, I'll look into it ...

**Comment by stefanwalther** [comment]
Hi, I have created a new and better Qlik Sense app with two examples and absolutely cannot see the problem. Where do you experience that, in Qlik Sense 1.1 or QlikSense 1.0.x?

Looks like it is working as expected:
![qscalendarview_twoinstances](https://cloud.githubusercontent.com/assets/669728/6428110/1896a692-bf95-11e4-9353-60f6a6dd2acc.png)

**Comment by stefanwalther** [comment]
Updated demo: 6cf92169746470342f45682d9a674a339a9541e4

**Comment by andre-ferreira-qlik** [comment]
1.1 works has expected, the issue is only in 1.0.2 really

**Comment by stefanwalther** [comment]
OK, will double-check ...
