### ISSUE TITLE
Sum(Dim)/Sum(Dim2) results in white calendar

### ISSUE THREAD

**Issue by ludberg** [stefanwalther/sense-calendar-heatmap#7]
Steps to reproduce:

1) In the Value field enter something like Sum(Dim)/Sum(Dim2).
2) In debug you'll see values but when switching back to normal mode the calendar is all white.

**Comment by stefanwalther** [comment]
I assume that you are talking about values from the sample script (Ctrl+0+0)??

**Comment by ludberg** [comment]
I used my own data/app and just took two Fields. In this case it was WorkedHours and TotalHours. 

Here are a few screens: http://imgur.com/a/xJYTL

I've tried using Sum(Example1.Open)/Sum(Example1.Close) from the demo-app and it works.

**Comment by andre-ferreira-qlik** [comment]
It might be the null values, the "-" on your screenshot, from memory i had to ensure those were excluded

**Comment by ludberg** [comment]
I can confirm that the null values caused the issue. 

Maybe null values could be grey or white because I dont want to just assign a number to the null rows.
