### ISSUE TITLE
White Calendar 

### ISSUE THREAD

**Issue by angerang** [stefanwalther/sense-calendar-heatmap#8]
Hi

I entered Sum([TotalNoOfEvents]) in the Value expression field and in debug I can see values but when switching back to normal mode the calendar is all white. 

![image](https://cloud.githubusercontent.com/assets/11007011/10861855/52bbdbfc-7fcb-11e5-812a-5539d23e2c96.png)

![image](https://cloud.githubusercontent.com/assets/11007011/10861857/6784e330-7fcb-11e5-80dd-9e9133501a22.png)

May I know what is wrong with this? 

Thank you!

**Comment by stefanwalther** [comment]
Hi, can you post/share some sample data, would then be easier to reproduce, thx.

**Comment by angerang** [comment]
Hi, I was unable to upload the qlik app and the data file. Here's a snapshot of the dataset and the codes in qlik. 

Data: 
![image](https://cloud.githubusercontent.com/assets/11007011/10866701/7c353580-8077-11e5-96c7-93d47c7fb884.png)

First code in Qlik: (Changed the format of the date) 
![image](https://cloud.githubusercontent.com/assets/11007011/10866707/ce98541a-8077-11e5-8c6a-d16c823ab6ba.png)

Reading the dataset: 
![image](https://cloud.githubusercontent.com/assets/11007011/10866709/e0347582-8077-11e5-98c0-0d5fccc32ce9.png)

For the master calendar:
![image](https://cloud.githubusercontent.com/assets/11007011/10866710/f0bf56e2-8077-11e5-83e6-abc28c2fca35.png)

The fields and values for the calendar. 
![image](https://cloud.githubusercontent.com/assets/11007011/10866711/fb6fb9d8-8077-11e5-9d4d-1f2ac621b5ed.png)

Thank you!

**Comment by cray74** [comment]
Hi,

same problem here. No empty datapoints, data in debug mode looks OK, calendar still empty :(.

![calendar_heatmap_data jpg](https://cloud.githubusercontent.com/assets/2738654/11299246/820c6448-8f85-11e5-880d-0b52e0c80c14.jpg)

![calendar_heatmap jpg](https://cloud.githubusercontent.com/assets/2738654/11299263/aa3ad9a4-8f85-11e5-9c56-658394748ef3.jpg)

Thanks a lot for your help (and the great extension!).
